// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoRoC3bo4Wpif7yJz9kP8flN4jJbDwOkI',
    appId: '1:439406979685:web:9d4cae105d2e1ebaa8748c',
    messagingSenderId: '439406979685',
    projectId: 'meko-kehnu-a081b',
    authDomain: 'meko-kehnu-a081b.firebaseapp.com',
    storageBucket: 'meko-kehnu-a081b.appspot.com',
    measurementId: 'G-MV3NNW3JY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIZT0vS0XOehb4hPWV4L41R8BpP8QY8UE',
    appId: '1:439406979685:android:ec2b649675f8928ba8748c',
    messagingSenderId: '439406979685',
    projectId: 'meko-kehnu-a081b',
    storageBucket: 'meko-kehnu-a081b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMqRRHowF8YAe8TpUIrVfX7zb_TpvX7CU',
    appId: '1:439406979685:ios:c4ba1f77ac573cf8a8748c',
    messagingSenderId: '439406979685',
    projectId: 'meko-kehnu-a081b',
    storageBucket: 'meko-kehnu-a081b.appspot.com',
    iosClientId: '439406979685-jf3diise8o9o6km9j7qq4jm0egnegucv.apps.googleusercontent.com',
    iosBundleId: 'com.example.meko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMqRRHowF8YAe8TpUIrVfX7zb_TpvX7CU',
    appId: '1:439406979685:ios:c4ba1f77ac573cf8a8748c',
    messagingSenderId: '439406979685',
    projectId: 'meko-kehnu-a081b',
    storageBucket: 'meko-kehnu-a081b.appspot.com',
    iosClientId: '439406979685-jf3diise8o9o6km9j7qq4jm0egnegucv.apps.googleusercontent.com',
    iosBundleId: 'com.example.meko',
  );
}
